baseURL = "https://riktapsykiatri.se/"
languageCode = "sv"
title = "Rikta Psykiatri"
defaultContentLanguage = "sv"
defaultContentLanguageInSubdir = false
enableRobotsTXT = true
disableKinds = ["taxonomy","term"]   # no taxonomies for this one-page site

[languages]
  [languages.sv]
    languageName = "Svenska"
    weight = 1
  [languages.en]
    languageName = "English"
    languageCode = "en"
    title = "Rikta Psychiatry"
    weight = 2

[params]
  primary = "#000000"
  background = "#FFFFFF"
  secondary = "#4773A6"
  accent = "#DA5B5F"
  stickyHeaderOffset = 72
  logo = "/img/logo.png"
  hero = "/img/psychologist-picture.jpg"

[markup]
  [markup.goldmark.renderer]
    unsafe = true                    # allow HTML in Markdown (sections/forms)

[outputs]
  home = ["HTML","RSS","JSON"]

# Optional: silence the "raw HTML omitted" warning
ignoreLogs = ['warning-goldmark-raw-html']

# Optional: if you want GA later:
#[services]
#  [services.googleAnalytics]
#    id = ""
